= Obi-Wan Kinobi

Ein einfaches Filmpflege dingens für kleine Programmkinos.

== Setup für Entwickler

```bash
composer install
yarn
```

Kopiere .env.example zu .env.

Passe dort die Einstellungen für die Datenbank an.

Wer die Anwendung lieber in Docker-Containern ausführen will, schaue sich https://laradock.io/introduction/[laradock] an.

Dies sind die in .env zu ändernden Standardeinstellungen für die Datenbank:

```
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=homestead
DB_USERNAME=homestead
DB_PASSWORD=secret
```

Generiere einen Schlüssel für Sessions und Verschlüsselung (wird in die .env Datei geschrieben)

```bash
php artisan key:generate
```

Um Deine Installation zu testen, starte `php artisan serve` und rufe http://localhost:8000 im Browser auf.

== Tools

=== Aufräum Script

Folgendes Script führt untenstehende cs-fixer und ide-helper tasks aus:

```bash
./cleanup.sh
```

==== CS Fixer

Um Code Style Fixes für die php Dateien durchzuführen:

```bash
vendor/bin/php-cs-fixer fix
```

==== IDE Helper generieren

Um Deine IDE zu unterstützen, die fortgeschrittenen Aspekte von laravel zu verstehen, lass folgende Scripte laufen,
nachdem Du Deine Eloquent Models verändert hast:

```bash
./artisan clear-compiled && ./artisan ide-helper:generate && ./artisan ide-helper:models --write && ./artisan ide-helper:meta
```
